[WM_SpawnManager.SpawnManager]
Interval=3
ZedIncreasePerWave=1
ZedIncreasePerPlayer=0.5

[WM_SpawnManager.GameSetups]
MaxWave=(Setup=0, Value=255)
InitialDosh=(Setup=0, Value=500)
TraderTime=(Setup=0, Value=60)
bStartWithTrader=(Setup=0, Value=false)
ZedHealthScale=(Setup=0, Value=1.0)
XpScale=(Setup=0, Value=1.0)
DoshScale=(Setup=0, Value=1.0)
ExtraSpawnPerWave=(Setup=0, Value=0.05)
ExtraSpawnPerPlayer=(Setup=0, Value=0.5)
MaxAlive=(Setup=0, Value=30)
Interval=(Setup=0, Value=3)

MaxWave=(Setup=1, Value=10)
InitialDosh=(Setup=1, Value=2000)
TraderTime=(Setup=1, Value=20)
bStartWithTrader=(Setup=1, Value=true)
ZedHealthScale=(Setup=1, Value=2.0)
XpScale=(Setup=1, Value=2.0)
DoshScale=(Setup=1, Value=0.5)
ExtraSpawnPerWave=(Setup=1, Value=0.01)
ExtraSpawnPerPlayer=(Setup=1, Value=0.8)
MaxAlive=(Setup=1, Value=60)
Interval=(Setup=1, Value=6)
; == Common properties in the spawn list ==
; Setup: the setup to which this spawn belongs.
; Priority: Zeds with higher priority are spawned first.
; Count: Number of Zeds to spawn.

; These are spawned from the first wave
[WM_SpawnManager.RegularWaves]
Spawn=(Setup=0, Wave=1, ZedClass="KFPawn_ZedClot", Count=1, Priority=2)
Spawn=(Setup=0, Wave=1, ZedClass="KFPawn_ZedScrake", Count=2, Priority=1)
Spawn=(Setup=0, Wave=2, ZedClass="KFPawn_ZedClot", Count=1, Priority=2)
Spawn=(Setup=0, Wave=2, ZedClass="KFPawn_ZedScrake", Count=2, Priority=1)

Spawn=(Setup=1, Wave=1, ZedClass="KFPawn_ZedCrawler", Count=1, Priority=2)
Spawn=(Setup=1, Wave=1, ZedClass="KFPawn_ZedFleshpound", Count=2, Priority=1)
Spawn=(Setup=1, Wave=2, ZedClass="KFPawn_ZedCrawler", Count=1, Priority=2)
Spawn=(Setup=1, Wave=2, ZedClass="KFPawn_ZedFleshpound", Count=2, Priority=1)

; These are spawned after all the spawns from SpawnPresets.Regular finish.
; At the beginning each wave, one group is randomly selected and all the spawns in that group are spawned.
; This could be used to simulate the vanilla special waves, e.g. scrake, bloat, husk waves, in endless mode.
;
; The chance of each group being selected = frequency of that group / sum of frequencies of all groups.
; e.g. if you have Group=(Number=0, frequency=1) and Group=(Number=1, frequency=2), then the chance of Group 0 being selected is 1/(1+2) = 33.3%, 
;  and the chance of Group 1 being selected is 2/(1+2) = 66.6%.
[WM_SpawnManager.RandomWaves]
Wave=(Setup=0, Number=0, Frequency=1)
Spawn=(Wave=0, ZedClass="KFPawn_ZedBloat", Count=1, Priority=1)

Wave=(Setup=0, Number=1, Frequency=2)
Spawn=(Wave=1, ZedClass="KFPawn_ZedHusk", Count=1, Priority=1)

; These are spawned every X waves, where X is the value of BosswaveInterval.
; Can be used to simulate the vanilla boss waves in endless mode, but without the spawning animation.
; The function of Group number and frequency is the same as those in RandomWaves
[WM_SpawnManager.IntervalWaves]
Wave=(Setup=0, Number=0, Frequency=1)
Spawn=(Wave=0, ZedClass="KFPawn_ZedHans", Count=1, Priority=1)
Wave=(Setup=0, Number=1, Frequency=1)
Spawn=(Wave=1, ZedClass="KFPawn_ZedPatriarch", Count=1, Priority=1)