[ConfigurableGameMode.CGM_Survival]
bEnableDoshExt=true

[ConfigurableGameMode.CGM_SpawnManager]
Version=1.0

[ConfigurableGameMode.GameSetups]
DisplayMode=(Setup=0, Value=0)              ; Game mode shown in the server browser. 0 for Survival, 1 for Endless
MaxWave=(Setup=0, Value=255)                ; this is what you think it is.
InitialDosh=(Setup=0, Value=500)            ; this is what you think it is.
TraderTime=(Setup=0, Value=10)              ; this is what you think it is.
bStartWithTrader=(Setup=0, Value=true)     ; this is what you think it is.
InitialTraderTime=(Setup=1, Value=60)
XpScale=(Setup=0, Value=1.5)                ; Multiplier of the amount of XP players receive.
ExtraXpPerWave=(Setup=0, Value=0.5)
DoshScale=(Setup=0, Value=1.0)              ; Multiplier of the amount of Dosh players receive.
ExtraSpawnPerWave=(Setup=0, Value=1.0)     ; Additional spawns per wave.
ExtraSpawnPerPlayer=(Setup=0, Value=0.75)    ; Additional spawns per player.
MaxAlive=(Setup=0, Value=30)                ; Maximum number of Zeds alive at once.
Interval=(Setup=0, Value=10)                 ; Interval for interval waves.
ZedHealthScale=(Setup=0, Value=1.0)         ; Base health scale for Zeds from the first wave. 
ExtraHealthPerWave=(Setup=0, Value=0.05)     ; Additional health scale per wave, added to the base health scale.
ExtraHealthPerPlayer=(Setup=0, Value=0.5)   ; Additional health scale per player, added to the base health scale.
MaxHealthScale=(Setup=0, Value=10.0)        ; Maximum health scale that can be reached by adding the extra health per wave and per player. 0 for no limit.
ZedResistanceScale=(Setup=0, Value=1.0)
ExtraResistancePerWave=(Setup=0, Value=0.0)
MaxResistanceScale=(Setup=0, Value=10.0)
ZedDamageScale=(Setup=0, Value=1.0)
ExtraDamagePerWave=(Setup=0, Value=0.1)
MaxDamageScale=(Setup=0, Value=10.0)
ZedSpeedScale=(Setup=0, Value=1.0)
ExtraSpeedPerWave=(Setup=0, Value=0.05)
MaxSpeedScale=(Setup=0, Value=10.0)
bUseStockScaling=(Setup=0, Value=false)     ; If set to true, the vanilla scaling will be applied first and then multiplied by the custom scaling values.
bEnableBossWaves=(Setup=0, Value=false)      ; When enabled, interval waves will behave like the boss waves in vanilla endless mode.

DisplayMode=(Setup=1, Value=0)
MaxWave=(Setup=1, Value=100)
InitialDosh=(Setup=1, Value=10000)
TraderTime=(Setup=1, Value=20)
bStartWithTrader=(Setup=1, Value=true)
InitialTraderTime=(Setup=1, Value=60)
XpScale=(Setup=1, Value=1.0)
ExtraXpPerWave=(Setup=0, Value=0.5)
DoshScale=(Setup=1, Value=0.5)
ExtraSpawnPerWave=(Setup=1, Value=0.2)
ExtraSpawnPerPlayer=(Setup=1, Value=0.75)
MaxAlive=(Setup=1, Value=60)
Interval=(Setup=1, Value=5)
ZedHealthScale=(Setup=1, Value=3.0)
ExtraHealthPerWave=(Setup=1, Value=0.05)
ExtraHealthPerPlayer=(Setup=1, Value=0.3)
MaxHealthScale=(Setup=1, Value=999.0)
ZedResistanceScale=(Setup=1, Value=1.0)
ExtraResistancePerWave=(Setup=1, Value=0.0)
MaxResistanceScale=(Setup=1, Value=1.0)
ZedDamageScale=(Setup=1, Value=2.0)
ExtraDamagePerWave=(Setup=1, Value=0.05)
MaxDamageScale=(Setup=1, Value=999.0)
ZedSpeedScale=(Setup=1, Value=1.0)
ExtraSpeedPerWave=(Setup=1, Value=0.02)
MaxSpeedScale=(Setup=1, Value=10.0)
bUseStockScaling=(Setup=1, Value=false)
bEnableBossWaves=(Setup=1, Value=false)

; endless
DisplayMode=(Setup=2, Value=0)
MaxWave=(Setup=2, Value=4)
InitialDosh=(Setup=2, Value=999999)
TraderTime=(Setup=2, Value=6)
bStartWithTrader=(Setup=2, Value=true)
InitialTraderTime=(Setup=2, Value=120)
XpScale=(Setup=2, Value=1.0)
DoshScale=(Setup=2, Value=5.0)
ExtraSpawnPerPlayer=(Setup=2, Value=2.0)
MaxAlive=(Setup=2, Value=24)
ZedHealthScale=(Setup=2, Value=2.0)
ExtraHealthPerWave=(Setup=2, Value=0.05)
ExtraHealthPerPlayer=(Setup=2, Value=0.3)
MaxHealthScale=(Setup=2, Value=999.0)
ZedResistanceScale=(Setup=2, Value=1.0)
ExtraResistancePerWave=(Setup=2, Value=0.0)
MaxResistanceScale=(Setup=2, Value=1.0)
ZedDamageScale=(Setup=2, Value=2.0)
ExtraDamagePerWave=(Setup=2, Value=0.05)
MaxDamageScale=(Setup=2, Value=999.0)
ZedSpeedScale=(Setup=2, Value=3.0)
bUseStockScaling=(Setup=2, Value=false)

; mod testing
DisplayMode=(Setup=3, Value=0)
MaxWave=(Setup=3, Value=300)
InitialDosh=(Setup=3, Value=999999)
TraderTime=(Setup=3, Value=5)
bStartWithTrader=(Setup=3, Value=true)
XpScale=(Setup=3, Value=10.0)
DoshScale=(Setup=3, Value=10)
ExtraSpawnPerWave=(Setup=3, Value=0.2)
ExtraSpawnPerPlayer=(Setup=3, Value=0.75)
MaxAlive=(Setup=3, Value=60)
Interval=(Setup=3, Value=5)
ZedHealthScale=(Setup=3, Value=1000.0)
ExtraHealthPerWave=(Setup=3, Value=0.05)
ExtraHealthPerPlayer=(Setup=3, Value=0.3)
MaxHealthScale=(Setup=3, Value=1000.0)
ZedResistanceScale=(Setup=3, Value=1.0)
ExtraResistancePerWave=(Setup=3, Value=0.0)
MaxResistanceScale=(Setup=3, Value=1.0)
ZedDamageScale=(Setup=3, Value=2.0)
ExtraDamagePerWave=(Setup=3, Value=0.05)
MaxDamageScale=(Setup=3, Value=999.0)
ZedSpeedScale=(Setup=3, Value=1.0)
ExtraSpeedPerWave=(Setup=3, Value=0.02)
MaxSpeedScale=(Setup=3, Value=10.0)
bUseStockScaling=(Setup=3, Value=false)
bEnableBossWaves=(Setup=3, Value=false)

; stress testing
DisplayMode=(Setup=4, Value=0)
MaxWave=(Setup=4, Value=10)
InitialDosh=(Setup=4, Value=999999)
TraderTime=(Setup=4, Value=30)
bStartWithTrader=(Setup=4, Value=true)
XpScale=(Setup=4, Value=10.0)
DoshScale=(Setup=4, Value=10)
ExtraSpawnPerWave=(Setup=4, Value=0.2)
ExtraSpawnPerPlayer=(Setup=4, Value=0.75)
MaxAlive=(Setup=4, Value=96)
Interval=(Setup=4, Value=5)
ZedHealthScale=(Setup=4, Value=3.0)
ExtraHealthPerWave=(Setup=4, Value=0.05)
ExtraHealthPerPlayer=(Setup=4, Value=0.3)
MaxHealthScale=(Setup=4, Value=100.0)
ZedResistanceScale=(Setup=4, Value=1.0)
ExtraResistancePerWave=(Setup=4, Value=0.0)
MaxResistanceScale=(Setup=4, Value=1.0)
ZedDamageScale=(Setup=4, Value=2.0)
ExtraDamagePerWave=(Setup=4, Value=0.05)
MaxDamageScale=(Setup=4, Value=999.0)
ZedSpeedScale=(Setup=4, Value=1.0)
ExtraSpeedPerWave=(Setup=4, Value=0.02)
MaxSpeedScale=(Setup=4, Value=10.0)
bUseStockScaling=(Setup=4, Value=false)
bEnableBossWaves=(Setup=4, Value=false)
; == Common properties in the spawn list ==
; Setup: the setup to which this spawn belongs.
; Priority: Zeds with higher priority are spawned first.
; Count: Number of Zeds to spawn.

; These are spawned from the first wave
[ConfigurableGameMode.RegularWaves]
Spawn=(Setup=0, Wave=0, ZedClass="KFGameContent.KFPawn_ZedHusk", Count=1, Priority=1)

Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteSlasher", Count=5, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteClotAlpha", Count=5, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteBloat", Count=3, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteClotAlpha", Count=3, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteSiren", Count=2, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteClotAlphaKing", Count=1, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteCrawler", Count=3, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteCrawlerGas", Count=1, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteGorefast", Count=1, Priority=1)
Spawn=(Setup=1, Wave=0, ZedClass="EliteZeds2.KFPawn_EliteGorefiend", Count=1, Priority=1)
; Spawn=(Setup=1, Wave=2, ZedClass="ConfigurableGameMode.CGM_ZedHans", Count=3, Priority=2)
; Spawn=(Setup=1, Wave=3, ZedClass="ConfigurableGameMode.CGM_ZedFleshpoundKing", Count=3, Priority=2)
; Spawn=(Setup=1, Wave=4, ZedClass="ConfigurableGameMode.CGM_ZedBloatKing", Count=3, Priority=2)
; Spawn=(Setup=1, Wave=5, ZedClass="ConfigurableGameMode.CGM_ZedMatriarch", Count=3, Priority=2)

; Spawn=(Setup=2, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Shock", Count=5, Priority=1)
; Spawn=(Setup=2, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Toxic", Count=5, Priority=1)
; Spawn=(Setup=2, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Frozen", Count=5, Priority=1)
; Spawn=(Setup=2, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Hell", Count=5, Priority=1)
; Spawn=(Setup=2, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Rusty", Count=5, Priority=1)

Spawn=(Setup=3, Wave=0, ZedClass="CGM_Zeds.CGM_DummyScrake", Count=1, Priority=1)
Spawn=(Setup=3, Wave=1, ZedClass="CGM_Zeds.CGM_DummyScrake", Count=1, Priority=1)

Spawn=(Setup=4, Wave=0, ZedClass="KFGameContent.KFPawn_ZedFleshpound", Count=500, Priority=1)

; These are spawned after all the spawns from SpawnPresets.Regular finish.
; At the beginning each wave, one group is randomly selected and all the spawns in that group are spawned.
; This could be used to simulate the vanilla special waves, e.g. scrake, bloat, husk waves, in endless mode.
;
; The chance of each group being selected = frequency of that group / sum of frequencies of all groups.
; e.g. if you have Group=(Number=0, frequency=1) and Group=(Number=1, frequency=2), then the chance of Group 0 being selected is 1/(1+2) = 33.3%, 
;  and the chance of Group 1 being selected is 2/(1+2) = 66.6%.
[ConfigurableGameMode.RandomWaves]
; ================= setup=0 =================
Wave=(Setup=0, Number=1, Type=0, Frequency=1)
Spawn=(Setup=0, Wave=1, ZedClass="KFGameContent.KFPawn_ZedHusk", Count=1, Priority=1)

; ================= setup=1 =================
Wave=(Setup=1, Number=1, Type=0, Frequency=1)
Spawn=(Setup=1, Wave=1, ZedClass="KFGameContent.KFPawn_EliteQuarterpound", Count=10, Priority=1, SquadSize=5)
Spawn=(Setup=1, Wave=1, ZedClass="KFGameContent.KFPawn_ZedFleshpound", Count=5, Priority=1, SquadSize=5)
Spawn=(Setup=1, Wave=1, ZedClass="EliteZeds2.KFPawn_EliteFleshpound", Count=3, Priority=1, SquadSize=5)
Spawn=(Setup=1, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Shock", Count=1, Priority=1, SquadSize=5)
Spawn=(Setup=1, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Hell", Count=1, Priority=1, SquadSize=5)
Spawn=(Setup=1, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Frozen", Count=1, Priority=1, SquadSize=5)
Spawn=(Setup=1, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Toxic", Count=1, Priority=1, SquadSize=5)
Spawn=(Setup=1, Wave=1, ZedClass="ZedternalRebornExt.WMPawn_ZedFleshpound_Rusty", Count=1, Priority=1, SquadSize=5)

Wave=(Setup=1, Number=2, Type=0, Frequency=1)
Spawn=(Setup=1, Wave=2, ZedClass="KFGameContent.KFPawn_ZedScrake", Count=10, Priority=1)
Spawn=(Setup=1, Wave=2, ZedClass="EliteZeds2.KFPawn_EliteScrake", Count=5, Priority=1)
Spawn=(Setup=1, Wave=2, ZedClass="ZedternalRebornExt.WMPawn_ZedScrake_Double", Count=3, Priority=1)
Spawn=(Setup=1, Wave=2, ZedClass="ZedternalRebornExt.WMPawn_ZedScrake_White", Count=3, Priority=1)
Spawn=(Setup=1, Wave=2, ZedClass="ZedternalRebornExt.WMPawn_ZedScrake_Double_BIG", Count=1, Priority=1)

Wave=(Setup=1, Number=3, Type=0, Frequency=1)
Spawn=(Setup=1, Wave=3, ZedClass="zedcustom.mrpelvis", Count=5, Priority=1)
; Spawn=(Setup=1, Wave=3, ZedClass="zedcustom.prowler", Count=5, Priority=1)
Spawn=(Setup=1, Wave=3, ZedClass="zedcustom.darkcreep", Count=2, Priority=1)
Spawn=(Setup=1, Wave=3, ZedClass="ZedternalRebornExt.WMPawn_ZedHellcrawler", Count=10, Priority=1)


Wave=(Setup=1, Number=4, Type=0, Frequency=1)
Spawn=(Setup=1, Wave=4, ZedClass="zedcustom.greenbloat", Count=10, Priority=1)
Spawn=(Setup=1, Wave=4, ZedClass="ZedternalRebornExt.WMPawn_ZedColdbloat", Count=2, Priority=1)
Spawn=(Setup=1, Wave=4, ZedClass="ZedternalRebornExt.WMPawn_ZedLavabloat", Count=2, Priority=1)
Spawn=(Setup=1, Wave=4, ZedClass="CGM_Zeds.CGM_ZedBloatKing", Count=1, Priority=99, MaxAliveToSpawn=1, SquadSize=1)

Wave=(Setup=1, Number=5, Type=0, Frequency=1)
Spawn=(Setup=1, Wave=5, ZedClass="KFPawn_ZedHusk", Count=5, Priority=1)
Spawn=(Setup=1, Wave=5, ZedClass="zedcustom.bluehusk", Count=1, Priority=1)
Spawn=(Setup=1, Wave=5, ZedClass="zedcustom.redhusk", Count=1, Priority=1)
Spawn=(Setup=1, Wave=5, ZedClass="zedcustom.shocktroop", Count=1, Priority=1)
Spawn=(Setup=1, Wave=5, ZedClass="zedcustom.sparky", Count=1, Priority=1)
Spawn=(Setup=1, Wave=5, ZedClass="zedcustom.mancubus", Count=1, Priority=0, MaxAliveToSpawn=1)

Wave=(Setup=1, Number=6, Type=0, Frequency=8)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteSlasher", Count=5, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteClotAlpha", Count=5, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteBloat", Count=3, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteClotAlpha", Count=3, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteSiren", Count=2, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteClotAlphaKing", Count=1, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteCrawler", Count=3, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteCrawlerGas", Count=1, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteGorefast", Count=2, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteGorefiend", Count=2, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteHusk", Count=2, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="EliteZeds2.KFPawn_EliteScrake", Count=2, Priority=1)
Spawn=(Setup=1, Wave=6, ZedClass="KFGameContent.KFPawn_ZedFleshpound", Count=2, Priority=1)

Wave=(Setup=2, Number=0, Type=0, Frequency=10)
Spawn=(Setup=2, Wave=0, ZedClass="KFGameContent.KFPawn_ZedFleshpound", Count=100, Priority=99)
Spawn=(Setup=2, Wave=0, ZedClass="KFGameContent.KFPawn_ZedScrake", Count=100, Priority=99)
Spawn=(Setup=2, Wave=0, ZedClass="CGM_Zeds.CGM_ZedPatriarch", Count=10, Priority=1, SquadSize=1)

Wave=(Setup=3, Number=0, Type=0, Frequency=1)
Spawn=(Setup=3, Wave=0, ZedClass="none", Count=5, Priority=1)
; These are spawned every X waves, where X is the value of BosswaveInterval.
; Can be used to simulate the vanilla boss waves in endless mode, but without the spawning animation.
; The function of Group number and frequency is the same as those in RandomWaves
[ConfigurableGameMode.IntervalWaves]
Wave=(Setup=1, Number=0, Frequency=1)
Spawn=(Setup=1, Wave=0, ZedClass="CGM_Zeds.CGM_ZedHans", Count=1, Priority=99, SquadSize=1)
Spawn=(Setup=1, Wave=0, ZedClass="CGM_Zeds.CGM_ZedBloatKing", Count=1, Priority=99, SquadSize=1)
Spawn=(Setup=1, Wave=0, ZedClass="CGM_Zeds.CGM_ZedMatriarch", Count=1, Priority=99, SquadSize=1)
Spawn=(Setup=1, Wave=0, ZedClass="CGM_Zeds.CGM_ZedPatriarch", Count=1, Priority=99, SquadSize=1)
Spawn=(Setup=1, Wave=0, ZedClass="CGM_Zeds.CGM_ZedFleshpoundKing", Count=1, Priority=99, SquadSize=1)


; [ConfigurableGameMode.SpecialWaveModifier]
; Modifier=(Setup=0, Wave=5, ZedHealthScale=2.0, ZedDamageScale=2.0, ZedSpeedScale=1.5)